@Library('my-first-shared-library') _
pipeline {
    agent any
    environment {
        REPO = "app2-flask"
        TAG   = "${BUILD_NUMBER}"
        PORT = "5050"
    }

    stages {
        stage('build') {
            steps {
                buildImage()
            }
        }
        stage('deploy') {
            steps {
                deployApp()
            }
        }
    }
}
